import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kiky's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} antialiased`}
      >
        <main className="flex relative min-h-screen">
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger className="absolute top-0 right-0 m-4" />
            <div className="flex-1 flex justify-center p-4">
              {children}
            </div>
          </SidebarProvider>
        </main>
      </body>
    </html>
  );
}
